### ISSUE TITLE
github id가 대문자인 경우 API 호출이 불가능

### ISSUE THREAD

**Issue by KS-KIM** [woowa-supp/supp#13]
`User`, `Surveyee` 테이블에는 github id가 지정된 대로 저장된다. (대문자와 소문자 혼용)

하지만, techcourse.woowahan.com 에서는 github id를 소문자로 저장하기 때문에 API 호출의 용이성을 위해 소문자로 저장할 필요가 있다.

* 대문자 ID를 가지는 유저 조회
![image](https://user-images.githubusercontent.com/20358042/79684868-8a360c00-826f-11ea-9e43-6991679211de.png)

* 소문자 ID로 API 요청할 경우 Error 발생
![image](https://user-images.githubusercontent.com/20358042/79684889-b18cd900-826f-11ea-91dd-f4b72cc6d3cf.png)

**Comment by toneyparky** [comment]
소문자 아이디 -> DB에 소문자로 저장
대문자 아이디 -> DB에 대문자로 저장

이런 상황인데 저장자체도 대문자나 소문자로 통일하고,
조회시에 파라미터로 받은 대문자건 소문자건 아이디를 통일한걸 바탕으로 조회하자?

**Comment by KS-KIM** [comment]
> 소문자 아이디 -> DB에 소문자로 저장
> 대문자 아이디 -> DB에 대문자로 저장
> 
> 이런 상황인데 저장자체도 대문자나 소문자로 통일하고,
> 조회시에 파라미터로 받은 대문자건 소문자건 아이디를 통일한걸 바탕으로 조회하자?

OK.

**Comment by toneyparky** [comment]
오.. 
로직 맞음?
아에 다 소문자로 고고하자는 거구만

---

우선 주관신 처리하고 커밋부터 할겡

**Comment by kouz95** [comment]
https://stackoverflow.com/questions/37178520/jpql-like-case-insensitive

**Comment by toneyparky** [comment]
Surveyee생성시 login을 소문자로 바꾸어서 생성하도록 처리했습니다.

![image](https://user-images.githubusercontent.com/37579660/81037178-bc38a680-8edc-11ea-8339-bda9d9b2a7cc.png)
