### ISSUE TITLE
설문 페이지 localStroage type set 이후 (type이 결정 되는 순간)

### ISSUE THREAD

**Issue by kouz95** [woowa-supp/supp#5]
결정 된 이후 다른 설문 (타입 말고 페어에 도움 되는 질문지)
로 넘어가는 기능 구현 하지 않았습니다.
현재 결정 된 이후에 답변 버튼을 계속 누르게 되는 경우 다른 질문으로 넘어가는 (트리를 다시 타는) 문제가 있습니다.
localStorage.set 이후 다음 검사 페이지로 넘어가게 되면 문제 안될거라고 생각합니다.

**Comment by toneyparky** [comment]
이 문제에 대해서 어제 발견하여 스티치와 또링에게 공유했고, 오늘 공유하려했는데 이미 인지하고 있었군요.
역시 코즈 멋있습니다👍
수정 완료되면 이슈 클로즈 부탁드려요~

**Comment by kouz95** [comment]
수정 완료
