### ISSUE TITLE
테스트 코드 작성 및 Controller, Service 리팩토링

### ISSUE THREAD

**Issue by kouz95** [woowa-supp/supp#84]
- 테스트 코드 작성
- Controller 리팩토링
   - exception 제거
- Service 리팩토링
   - 불필요한 save 호출 제거

현재 Controller에서 ResponseEntity 반환이 아닌 Long 또는 Dto를 반환하고 있습니다.
이 부분은 api를 사용하는 쪽과의 논의가 필요하다고 판단하여 변경하지 않겠습니다.

**Comment by toneyparky** [comment]
지금 프론트 구현은 api 통신 없이 진행중입니다.
내일까지 뼈대를 만들고 api를 논의해서 붙여보도록 하죠..!
